### ISSUE TITLE
Evaluation visualization

### ISSUE THREAD

**Issue by priyasundaresan** [UT-Austin-RPL/MUTEX#3]
Thanks for open-sourcing MUTEX & for the great codebase! A quick question -- in mutex/eval.py, it looks like summary2video is not defined anywhere, do you mind updating this?

Thanks a lot!

**Comment by ShahRutav** [comment]
Hi, thanks for your interest in our work.
I have fixed #4 the issue with evaluation visualization. You should be able to save evaluation rollout videos using the flag `save_video=True`. Let me know if you encounter any issues.

**Comment by ShahRutav** [comment]
Closing this issue. Feel free to open it!
