### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by BrightMoonStar** [UT-Austin-RPL/MUTEX#5]
Hi, I can't seem to download the dataset~

![image](https://github.com/UT-Austin-RPL/MUTEX/assets/144759751/c2855d20-752d-40db-9927-30d99ffb71d8)

**Comment by ShahRutav** [comment]
This seems to be an issue with the box. An easier way to download the dataset from the command line is using [boxcli](https://github.com/box/boxcli). Can you check if that works for you?

**Comment by BrightMoonStar** [comment]
Thanks for your reply! I am trying to learn how to use boxcli , especially how to get the access token. Before this, I found that the sizes of the same type of files are very different. Is this normal? 
![image](https://github.com/UT-Austin-RPL/MUTEX/assets/144759751/f0f6014c-58bc-4b88-a3b3-0a88f98e4c3e)

**Comment by ShahRutav** [comment]
- To configure boxcli, I used the step 1 & 2 from [here](https://developer.box.com/guides/cli/quick-start/install-and-configure/)
- the file sizes look odd to me. I will take a look into this and get back to you.

**Comment by ShahRutav** [comment]
I have updated the files in the libero_100 folder. Let me know if you face any other issues. Thanks!

**Comment by BrightMoonStar** [comment]
Thanks for your contribution！ It would be better if the link address could be made permanent.

![image](https://github.com/UT-Austin-RPL/MUTEX/assets/144759751/670c7090-07b0-4eee-97f7-311f3b12430d)

**Comment by ShahRutav** [comment]
done

**Comment by BrightMoonStar** [comment]
Thank you very much!
