### ISSUE TITLE
The hdf5 file in debug folder is broken

### ISSUE THREAD

**Issue by lipeiyan-bd** [UT-Austin-RPL/MUTEX#6]
Hi, thank you for open-sourcing this excellent work! It appears that the HDF5 file in the debug folder may be corrupted. When I try to open it with `h5py.File()`, the system returns the following error:

`Error: Unable to synchronously open file (truncated file: eof = 94208, sblock->base_addr = 0, stored_eof = 463123000).`

Could you please update the dataset?

**Comment by ShahRutav** [comment]
I updated the file just now. Can you test it?

**Comment by lipeiyan-bd** [comment]
Thanks for your help! But it seems that the pretrained checkpoint also has some problems. When I run :
`MUJOCO_EGL_DEVICE_ID=0 CUDA_VISIBLE_DEVICES=0 python3 mutex/eval.py         benchmark_name=debug         folder=/home/data/mutex/         eval_spec_modalities=gl         experiment_dir=/home/mutex/Mutex_Models/mutex_pretrained         model_name=mutex_weights.pth`
The system gives the following errros:
```
    algo.policy.load_state_dict(torch_load_model(cfg.pretrain_model_path[ind], device=cfg.device)[0], strict=True)
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BCMutexPolicy:
        Unexpected key(s) in state_dict: "language_emb_model.text_model.embeddings.position_ids", "visual_emb_model.vision_model.embeddings.position_ids". 
```

**Comment by lipeiyan-bd** [comment]
Moreover, even if i set `strict=False` as:
`algo.policy.load_state_dict(torch_load_model(cfg.pretrain_model_path[ind], device=cfg.device)[0], strict=False)`
The system will give a new error:
/home/LIBERO/libero/libero/bddl_files/debug/KITCHEN_SCENE3_turn_on_the_stove.bddl does not exist!

**Comment by ShahRutav** [comment]
These are two different issues.
>Thanks for your help! But it seems that the pretrained checkpoint also has some problems. When I run :
MUJOCO_EGL_DEVICE_ID=0 CUDA_VISIBLE_DEVICES=0 python3 mutex/eval.py         benchmark_name=debug         folder=/home/data/mutex/         eval_spec_modalities=gl         experiment_dir=/home/mutex/Mutex_Models/mutex_pretrained         model_name=mutex_weights.pth 
The system gives the following errors

Can you verify if the Transformers library version used is `4.30.0`?

For the second error,
>Moreover, even if i set strict=False as:
algo.policy.load_state_dict(torch_load_model(cfg.pretrain_model_path[ind], device=cfg.device)[0], strict=False)
The system will give a new error:
/home/LIBERO/libero/libero/bddl_files/debug/KITCHEN_SCENE3_turn_on_the_stove.bddl does not exist!

It seems like the bddl file for the debug benchmark is missing. You can copy the bddl file from the corresponding `libero_90` or `libero_100` directory. I will also update the Libero codebase.
Assuming your `LIBERO` codebase is installed in `/home` directory, run the following command -
```
mkdir /home/LIBERO/libero/libero/bddl_files/debug && cp /home/LIBERO/libero/libero/bddl_files/libero_100/KITCHEN_SCENE3_turn_on_the_stove.bddl /home/LIBERO/libero/libero/bddl_files/debug/KITCHEN_SCENE3_turn_on_the_stove.bddl
```

**Comment by lipeiyan-bd** [comment]
Thank you! I have solved it!
